name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js (optional if using JS/TS)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run build
        run: echo "Add your build/test commands here"
